# Generated by Django 5.1.1 on 2024-09-19 03:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
