# Generated by Django 5.1.1 on 2024-11-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Đang chuẩn bị hàng'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'Xem xét'), ('published', 'công khai')], default='in_review', max_length=10),
        ),
    ]
